### ISSUE TITLE
Wrong package name ?

### ISSUE THREAD

**Issue by mattallty** [jordan-sussman/open-sesame#2]
Hello @jordan-sussman 

I think there has been a problem with this package publication on NPM:
https://www.npmjs.com/package/open-sesame 

Here is what I can see on NPM:
<img width="790" alt="Screenshot 2024-07-19 at 09 35 03" src="https://github.com/user-attachments/assets/841a0a96-d487-4cb8-aabe-a294a350f14d">

Update:
I looked at your package.json and saw you renamed to `flexi-drawer` but I can't install it because it's private.

So my question is... how to install it?

**Comment by jordan-sussman** [comment]
@mattallty thanks for reaching out! This isn't a published package on npm. Your screenshot is of something entirely different. `flexi-drawer` was the original name but does not influence this. To get this set up locally

1. Download directly from the repo or from a fork
2. In the root directory, run `npm install`. This will install all necessary dependencies to use this component, such as the radix dialog primitive. 
3. To run the example `npm run dev`.

The source code is available under the MIT license to use as needed. Hope that helps!
